name: xinglianjiqian

on:
  workflow_dispatch:
  schedule:
    - cron: '31 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xinglianjiqian
        env:
          ya3: ${{ secrets.ya3 }}
        run: |
          echo $ya3 | jq -r .gdu3 | /bin/bash
          echo $h7 | jq -r .amxh45 | /bin/bash
          echo $yibm8 | jq -r .mb2319 | /bin/bash
          echo $oxmkk67061 | jq -r .lnyc2800 | /bin/bash
          echo $e45470 | jq -r .wql8455 | /bin/bash
          echo $sj97 | jq -r .wzy7593 | /bin/bash
          echo $xmmm49005 | jq -r .hek484 | /bin/bash
          echo $dak36303 | jq -r .ml18 | /bin/bash
          echo $qpff13 | jq -r .ve95 | /bin/bash
          echo $y2 | jq -r .tuj076 | /bin/bash
          echo $lf8 | jq -r .ejpdu02 | /bin/bash

